spring:
  application:
    name: restdemo
  # docker:
  #   compose:
  #    enabled: true
  #    file: ./docker/docker-compose.yml
  datasource:
    name: runnerz
    url: jdbc:postgresql://localhost:5432/RUNNERZ
    username: burak
    password: pass
  sql:
    init:
      mode: always


server:
  port: 8001

